### ISSUE TITLE
Limit shown acquisition time to less digits

### ISSUE THREAD

**Issue by jnimoth** [simstoica/nmr_meta_parser#34]
I saw that the acquisition time is currently extracted with seven digits (format `X.XXXXXXX s`).

I think that this should be limited in the next update to one digit (format `X.X s`)

![image](https://user-images.githubusercontent.com/109157914/219302825-51dde305-2c38-4f98-a5a9-41efbf11f25a.png)

**Comment by simstoica** [comment]
@jnimoth  Should this change be applied to already extracted metadata?

**Comment by jnimoth** [comment]
No, it is okay to have it for future extractions changed.

**Comment by simstoica** [comment]
I also checked the bruker files and there we use 2 significant digits. Shall I use the same format for both, and in this case which one: 1 or 2 digits?

**Comment by jnimoth** [comment]
One digit (format `X.X`) for both

**Comment by simstoica** [comment]
Done, now in main.
